### PR TITLE
Add support for TLS

### PR DESCRIPTION
**Pull request by coderigo**
- Enable TLS terminated Zookeeper connections
- Support output logging in JSON format

### CODE REVIEW

**Review by carlpett — APPROVED** [review]
Thanks @coderigo, this looks great! :cake:

**Comment by coderigo** [comment]
Neat. Thank _you_ 👍

**Comment by coderigo** [comment]
@carlpett just went to pull the latest docker image from dockerhub but noticed it hadn't updated and the circleci pipeline shows it failed to release, at least to GH:
https://app.circleci.com/pipelines/github/carlpett/zookeeper_exporter/2/workflows/dce6dae2-5131-4672-a46c-ae1817301c0e/jobs/48
anything I can do to help the pipeline pass?

**Comment by carlpett** [comment]
It appears a couple of things have broken by updates to both DockerHub and CircleCI since this was last released. I'm trying to patch things up a bit now, a proper fix will be upcoming.

**Comment by carlpett** [comment]
Was a hack to do, but now there is a binary in the Github release, and both `latest` and `v1.1.0` tags should be up-to-date on Docker Hub.
Thanks for noticing!

**Comment by coderigo** [comment]
Neat. Thanks. I'll give pulling it another shot tomorrow. Not familiar with
circleci so sorry couldn't be much help.

**Pull request merged**
